### ISSUE TITLE
[Question] What is btrfs filesystem address

### ISSUE THREAD

**Issue by BurhanDanger** [archmirak/archlinux-fde-uefi#4]
```
root@archlinux ~ # btrfs filesystem show
Label: 'ARCH'  uuid: 304d620d-03a8-45c2-81f2-f08cb5d34ab5
        Total devices 1 FS bytes used 847.52MiB
        devid    1 size 19.90GiB used 4.02GiB path /dev/mapper/cryptbtrfs

root@archlinux ~ # btrfs filesystem show /dev/mapper/cryptbtrfs
Label: 'ARCH'  uuid: 304d620d-03a8-45c2-81f2-f08cb5d34ab5
        Total devices 1 FS bytes used 850.47MiB
        devid    1 size 19.90GiB used 4.02GiB path /dev/mapper/cryptbtrfs

root@archlinux ~ # btrfs filesystem df /dev/mapper/cryptbtrfs
ERROR: not a btrfs filesystem: /dev/mapper/cryptbtrfs
```

**Comment by archmirak** [comment]
If you're referring to what UUID you should use inside both crypttab and GRUB, then it's the UUID of the partition you've mapped to cryptbtrfs. Let's suppose you've created two partitions using parted: /dev/sda1 and /dev/sda2. If the LUKS container is created into /dev/sda2 and the btrfs is inside of it, the UUID would be the one of /dev/sda2.

**Comment by BurhanDanger** [comment]
I'm learning btrfs. So please bear with me. My question was btrfs doesn't recognise ``/dev/mapper/cryptbtrfs`` as a btrfs system. What do I use instead of that ?

**Comment by archmirak** [comment]
Sorry, I didn't understand the question. 'btrfs filesystem df /dev/mapper/cryptbtrfs' does not work because cryptbtrfs is not actually mounted, so there's no valid mount point, the subvolumes instead are mounted. If you want to make it work you should unmount all the subvolumes then run 'mount /dev/mapper/cryptbtrfs [mount point]' then it would work.

Here's an example:
![example](https://user-images.githubusercontent.com/29427788/31773110-f97f57a0-b4e1-11e7-9e13-d9d24e1da063.jpg)

Sorry for the screenshot, but I was using plain tty on virtualbox out of archiso.

**Comment by BurhanDanger** [comment]
Thanks. Understood. ``/dev/mapper/cryptbtrfs`` is mounted as ``/``
